# Generated by Codex on 2026-04-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(help_text='导出格式: md/pdf/docx/word/html', max_length=16)),
                ('report_mode', models.CharField(default='full', help_text='导出内容模式: brief/full', max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='QUEUED', help_text='导出状态', max_length=16)),
                ('storage_path', models.CharField(blank=True, help_text='对象存储路径或本地路径', max_length=1024, null=True)),
                ('download_url', models.CharField(blank=True, help_text='下载地址', max_length=1024, null=True)),
                ('error_message', models.TextField(blank=True, help_text='失败原因', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='关联报告', on_delete=django.db.models.deletion.CASCADE, related_name='export_records', to='reports.report')),
            ],
            options={
                'verbose_name': '报告导出记录',
                'verbose_name_plural': '报告导出记录',
                'db_table': 'report_export_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
