# Generated by Django 6.0.3 on 2026-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_dual_text_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='reproduction_code',
            field=models.TextField(blank=True, help_text='复现代码（适用于 akshare 等结构化数据来源）', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='原始来源链接（结构化数据来源可能没有 URL）', max_length=1024),
        ),
    ]
