# Generated by Django 6.0.3 on 2026-04-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(help_text='efeet thread_id', max_length=64, unique=True)),
                ('system_message', models.TextField(blank=True, default='', help_text='用于重建 thread 的 system prompt')),
                ('status', models.CharField(choices=[('IDLE', '空闲'), ('RUNNING', '运行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='IDLE', help_text='会话运行状态', max_length=16)),
                ('history_messages', models.JSONField(default=list, help_text='efeet thread.history 的序列化结果')),
                ('state_snapshot', models.JSONField(default=dict, help_text='除 messages 外的 thread.state 快照')),
                ('latest_user_message', models.TextField(blank=True, default='', help_text='最近一次用户输入')),
                ('latest_assistant_message', models.TextField(blank=True, default='', help_text='最近一次 AI 输出')),
                ('last_error', models.TextField(blank=True, default='', help_text='最近一次运行错误')),
                ('run_count', models.PositiveIntegerField(default=0, help_text='累计运行次数')),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='research.researchtask')),
            ],
            options={
                'verbose_name': '调研会话',
                'verbose_name_plural': '调研会话',
                'db_table': 'research_conversation',
            },
        ),
        migrations.CreateModel(
            name='ResearchConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(default=1, help_text='所属运行轮次')),
                ('message_index', models.PositiveIntegerField(help_text='消息在完整会话中的顺序号')),
                ('role', models.CharField(choices=[('HUMAN', '用户'), ('AI', 'AI'), ('TOOL', '工具')], help_text='消息角色', max_length=16)),
                ('message_type', models.CharField(help_text='LangChain 消息类型，如 human/ai/tool', max_length=32)),
                ('content', models.TextField(blank=True, default='', help_text='便于展示的消息文本')),
                ('payload', models.JSONField(default=dict, help_text='完整序列化后的消息载荷')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.researchconversation')),
            ],
            options={
                'verbose_name': '调研会话消息',
                'verbose_name_plural': '调研会话消息',
                'db_table': 'research_conversation_message',
                'ordering': ['message_index'],
                'unique_together': {('conversation', 'message_index')},
            },
        ),
    ]
