# Generated by Django 5.2.8 on 2026-05-05 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasksteplog",
            options={
                "ordering": ["sequence", "created_at"],
                "verbose_name": "任务步骤日志",
                "verbose_name_plural": "任务步骤日志",
            },
        ),
        migrations.AddField(
            model_name="researchtask",
            name="dispatch_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待调度"),
                    ("QUEUED", "已入队"),
                    ("STARTING", "启动中"),
                    ("RUNNING", "运行中"),
                    ("FINISHED", "已结束"),
                    ("FAILED", "调度失败"),
                    ("CANCELLED", "已取消"),
                ],
                default="PENDING",
                help_text="后台调度状态",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="finished_at",
            field=models.DateTimeField(
                blank=True, help_text="后台任务结束时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="last_error",
            field=models.TextField(
                blank=True, help_text="最近一次执行失败原因", null=True
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="queued_at",
            field=models.DateTimeField(
                blank=True, help_text="任务进入异步调度队列的时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, help_text="后台执行重试次数"),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="runner_token",
            field=models.CharField(
                blank=True,
                help_text="当前执行实例令牌，用于避免重复执行",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="后台任务开始执行时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="error_message",
            field=models.TextField(blank=True, help_text="步骤失败原因", null=True),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="finished_at",
            field=models.DateTimeField(blank=True, help_text="步骤结束时间", null=True),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="is_interactive",
            field=models.BooleanField(
                default=False, help_text="此步骤是否需要用户介入反馈"
            ),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="sequence",
            field=models.PositiveIntegerField(
                default=1, help_text="同一任务内的步骤顺序号"
            ),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="步骤开始时间"
            ),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="step_code",
            field=models.CharField(
                blank=True,
                help_text="步骤编码，用于归类与幂等跟踪",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tasksteplog",
            name="user_response",
            field=models.JSONField(
                blank=True, help_text="用户介入后的反馈数据", null=True
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="researchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待处理"),
                    ("SEARCHING", "检索中"),
                    ("ANALYZING", "分析中"),
                    ("WAITING_USER", "等待介入"),
                    ("COMPLETED", "已完成"),
                    ("FAILED", "失败"),
                    ("CANCELLED", "已取消"),
                ],
                default="PENDING",
                help_text="任务当前状态",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="scrapedcontent",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tasksteplog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
