# Generated by Django 6.0.3 on 2026-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchconversation_researchconversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksteplog',
            name='is_interactive',
            field=models.BooleanField(default=False, help_text='此步骤是否需要用户介入反馈'),
        ),
        migrations.AddField(
            model_name='tasksteplog',
            name='user_response',
            field=models.JSONField(blank=True, help_text='用户介入后的反馈数据', null=True),
        ),
        migrations.AlterField(
            model_name='researchtask',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('SEARCHING', '检索中'), ('ANALYZING', '分析中'), ('WAITING_USER', '等待介入'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', help_text='任务当前状态', max_length=16),
        ),
    ]
