# Generated by Codex on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_tasksteplog_is_interactive_tasksteplog_user_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtask',
            name='parent_task',
            field=models.ForeignKey(
                blank=True,
                help_text='父级调研任务；为空表示用户发起的主任务',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='child_tasks',
                to='research.researchtask',
            ),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='task_role',
            field=models.CharField(
                choices=[
                    ('PRIMARY', '主调研任务'),
                    ('CROSS_MODEL', '交叉验证模型子任务'),
                ],
                default='PRIMARY',
                help_text='任务角色，用于区分主任务与内部交叉验证子任务',
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name='researchtask',
            index=models.Index(fields=['parent_task', 'task_role'], name='research_task_parent_role_idx'),
        ),
        migrations.AddIndex(
            model_name='researchtask',
            index=models.Index(fields=['user', 'parent_task'], name='research_task_user_parent_idx'),
        ),
    ]
