# Generated by Django 6.0.3 on 2026-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchtask_parent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtask',
            name='search_params',
            field=models.JSONField(default=dict, help_text='检索参数: 时间范围/信息源权威度'),
        ),
    ]
