[project]
name = "8feet-backend"
version = "0.1.0"
description = "8Feet 商业对象智能深度调研分析平台后端服务"
readme = "README.md"
authors = [
    { name = "oNya", email = "oNya685@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "Django",
    "psycopg2-binary",
    "pylint",
    "pylint-django",
    "pillow",
    "requests",
    "pandas",
    "PyJWT",
    "django-redis",
    "PyYAML",
    "minio",
    "django-cors-headers",
    "python-dotenv",
    "channels",
    "channels-redis",
    "daphne",
    "celery[redis]",
    "python-docx",
    "reportlab",
]
