# Generated by Django 3.1.7 on 2026-04-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARN', '警告'), ('ERROR', '错误')], default='INFO', max_length=8)),
                ('module', models.CharField(help_text='来源模块', max_length=64)),
                ('message', models.TextField(help_text='日志消息')),
                ('stack_trace', models.TextField(blank=True, help_text='异常堆栈', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='操作类型: LOGIN/CREATE_TASK/VIEW_REPORT/...', max_length=64)),
                ('target_module', models.CharField(help_text='目标模块: users/research/reports/...', max_length=64)),
                ('target_id', models.IntegerField(blank=True, help_text='操作对象 ID', null=True)),
                ('detail', models.JSONField(default=dict, help_text='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_tokens', models.IntegerField(default=0, help_text='请求 Token 数')),
                ('response_tokens', models.IntegerField(default=0, help_text='响应 Token 数')),
                ('latency_ms', models.FloatField(default=0.0, help_text='调用延迟 (毫秒)')),
                ('status', models.CharField(default='SUCCESS', help_text='调用状态: SUCCESS/FAILED/TIMEOUT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='llm_manager.llmconfig')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to='research.researchtask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '模型调用日志',
                'verbose_name_plural': '模型调用日志',
                'db_table': 'llm_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('COMPANY', '公司'), ('STOCK', '股票'), ('PRODUCT', '商品')], max_length=16)),
                ('object_name', models.CharField(help_text='关注对象名称', max_length=256)),
                ('condition', models.JSONField(default=dict, help_text='提醒条件: 关键词/价格阈值/更新频率等')),
                ('notify_email', models.BooleanField(default=True, help_text='是否邮件同步推送')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='上次触发时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推送提醒设置',
                'verbose_name_plural': '推送提醒设置',
                'db_table': 'alert_setting',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('INFO', '调研信息'), ('REPORT', '调研报告'), ('MODEL', '大模型')], max_length=16)),
                ('item_id', models.IntegerField(help_text='收藏对象 ID (指向 ScrapedContent/Report/LLMConfig)')),
                ('folder', models.CharField(blank=True, help_text='自定义分类文件夹名', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
                'db_table': 'favorite',
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
