# Generated by Django 6.0.3 on 2026-04-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模型显示名称，如 GPT-4、Claude-3', max_length=128)),
                ('provider', models.CharField(help_text='模型供应商，如 OpenAI、Anthropic、百度', max_length=64)),
                ('model_id', models.CharField(help_text='模型版本标识，如 gpt-4-0613', max_length=128)),
                ('api_endpoint', models.CharField(blank=True, help_text='API 接口地址', max_length=512, null=True)),
                ('api_key_encrypted', models.CharField(blank=True, help_text='加密存储的 API Key（建议使用环境变量）', max_length=512, null=True)),
                ('params', models.JSONField(default=dict, help_text='调用参数: temperature, max_tokens, context_window 等')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('description', models.TextField(blank=True, help_text='模型推荐使用场景说明', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
                'db_table': 'llm_config',
            },
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='指定角色 (ADMIN/NORMAL)，与 user 互斥', max_length=16, null=True)),
                ('can_use', models.BooleanField(default=True, help_text='是否允许使用')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='llm_manager.llmconfig')),
                ('user', models.ForeignKey(blank=True, help_text='指定用户（为空则对全体生效）', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '模型使用权限',
                'verbose_name_plural': '模型使用权限',
                'db_table': 'model_permission',
            },
        ),
        migrations.CreateModel(
            name='ModelObjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('COMPANY', '公司'), ('STOCK', '股票'), ('PRODUCT', '商品')], help_text='调研对象类型', max_length=16)),
                ('is_default', models.BooleanField(default=False, help_text='是否为该类型的默认推荐模型')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_mappings', to='llm_manager.llmconfig')),
            ],
            options={
                'verbose_name': '模型对象映射',
                'verbose_name_plural': '模型对象映射',
                'db_table': 'model_object_mapping',
                'unique_together': {('llm_config', 'object_type')},
            },
        ),
    ]
