# Generated by Django 6.0.3 on 2026-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_manager', '0004_modelusage_model_snapshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelobjectmapping',
            options={'verbose_name': '模型场景推荐', 'verbose_name_plural': '模型场景推荐'},
        ),
        migrations.AlterModelOptions(
            name='modelpermission',
            options={'verbose_name': '模型用户权限', 'verbose_name_plural': '模型用户权限'},
        ),
        migrations.AlterField(
            model_name='modelobjectmapping',
            name='is_default',
            field=models.BooleanField(default=False, help_text='是否为该场景下的默认模型'),
        ),
    ]
