# Generated by Django 6.0.3 on 2026-04-05 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('expires_by', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '认证记录',
                'verbose_name_plural': '认证记录',
                'db_table': 'auth_record',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, help_text='头像 URL (Minio 路径)', max_length=512, null=True)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=20, null=True)),
                ('organization', models.CharField(blank=True, help_text='所属单位/组织', max_length=256, null=True)),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('NORMAL', '普通用户')], default='NORMAL', help_text='用户角色: ADMIN 或 NORMAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='关联 Django 内置 User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profile',
                'permissions': [('create_user', '创建用户账户'), ('update_user', '修改用户信息及角色'), ('toggle_user', '启用/禁用用户账户'), ('view_user', '查看用户列表')],
            },
        ),
    ]
