# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_align_user_profile_frontend_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersona",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_markdown", models.TextField(blank=True, default="", help_text="AI 生成的人设分析报告 Markdown")),
                ("summary", models.TextField(blank=True, default="", help_text="人设摘要，便于列表或上下文显示")),
                ("source_thread_id", models.CharField(blank=True, default="", help_text="最近一次生成人设的 efeet thread_id", max_length=64)),
                ("model_id", models.CharField(blank=True, default="", help_text="最近一次生成人设使用的平台模型 ID", max_length=64)),
                ("skipped_at", models.DateTimeField(blank=True, help_text="用户跳过新手人设引导的时间", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(help_text="关联用户", on_delete=django.db.models.deletion.CASCADE, related_name="persona", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "用户人设",
                "verbose_name_plural": "用户人设",
                "db_table": "user_persona",
            },
        ),
        migrations.CreateModel(
            name="UserPersonaConversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("thread_id", models.CharField(help_text="efeet thread_id", max_length=64, unique=True)),
                ("model_id", models.CharField(help_text="平台模型 ID", max_length=64)),
                ("system_message", models.TextField(blank=True, default="", help_text="用于恢复 thread 的 system prompt")),
                ("status", models.CharField(choices=[("DRAFT", "草稿"), ("COMPLETED", "已完成"), ("FAILED", "失败")], default="DRAFT", help_text="会话状态", max_length=16)),
                ("history_messages", models.JSONField(default=list, help_text="efeet thread.history 序列化结果")),
                ("state_snapshot", models.JSONField(default=dict, help_text="efeet thread.state 快照")),
                ("latest_user_message", models.TextField(blank=True, default="")),
                ("latest_assistant_message", models.TextField(blank=True, default="")),
                ("last_error", models.TextField(blank=True, default="")),
                ("presented_report_path", models.CharField(blank=True, default="", max_length=512)),
                ("presented_report_markdown", models.TextField(blank=True, default="")),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(help_text="关联用户", on_delete=django.db.models.deletion.CASCADE, related_name="persona_conversations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "用户人设设定对话",
                "verbose_name_plural": "用户人设设定对话",
                "db_table": "user_persona_conversation",
                "ordering": ["-created_at"],
            },
        ),
    ]
