# Generated by Django 3.1.7 on 2026-04-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='报告标题', max_length=256)),
                ('summary', models.TextField(help_text='报告摘要')),
                ('content_markdown', models.TextField(help_text='报告正文 (Markdown 格式，详版)')),
                ('content_brief', models.TextField(blank=True, help_text='报告简版内容', null=True)),
                ('file_pdf_path', models.CharField(blank=True, help_text='PDF 文件路径 (Minio)', max_length=512, null=True)),
                ('file_word_path', models.CharField(blank=True, help_text='Word 文件路径 (Minio)', max_length=512, null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='报告版本号')),
                ('is_latest', models.BooleanField(default=True, help_text='是否为最新版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='关联的调研任务', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='research.researchtask')),
            ],
            options={
                'verbose_name': '调研报告',
                'verbose_name_plural': '调研报告',
                'db_table': 'report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='用户提出的追问')),
                ('answer', models.TextField(blank=True, help_text='系统生成的回答', null=True)),
                ('context_paragraph', models.TextField(blank=True, help_text='追问所针对的报告段落', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报告追问',
                'verbose_name_plural': '报告追问',
                'db_table': 'report_followup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveIntegerField(help_text='引用角标编号 (如 [1], [2])')),
                ('source_url', models.URLField(help_text='原始来源链接', max_length=1024)),
                ('source_title', models.CharField(help_text='来源标题', max_length=512)),
                ('cited_text_snippet', models.TextField(blank=True, help_text='报告中引用的文本片段', null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='reports.report')),
            ],
            options={
                'verbose_name': '引用来源',
                'verbose_name_plural': '引用来源',
                'db_table': 'citation',
                'ordering': ['index_number'],
                'unique_together': {('report', 'index_number')},
            },
        ),
    ]
