# Generated by Django 3.1.7 on 2026-04-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='调研任务标题', max_length=256)),
                ('object_name', models.CharField(help_text='调研对象名称（公司名/股票代码/商品名）', max_length=256)),
                ('object_type', models.CharField(choices=[('COMPANY', '公司'), ('STOCK', '股票'), ('PRODUCT', '商品')], help_text='调研对象类型', max_length=16)),
                ('search_params', models.JSONField(default=dict, help_text='检索参数: 时间范围/信息源权威度/研究深度')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('SEARCHING', '检索中'), ('ANALYZING', '分析中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', help_text='任务当前状态', max_length=16)),
                ('progress', models.JSONField(default=dict, help_text='各阶段完成度: {searching: 80, analyzing: 0, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_config', models.ForeignKey(blank=True, help_text='用户选择的大模型配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_tasks', to='llm_manager.llmconfig')),
                ('user', models.ForeignKey(help_text='发起调研的用户', on_delete=django.db.models.deletion.CASCADE, related_name='research_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '调研任务',
                'verbose_name_plural': '调研任务',
                'db_table': 'research_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStepLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text="步骤名称，如 '拆解问题'、'检索信息'、'分析数据'", max_length=256)),
                ('step_status', models.CharField(choices=[('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('PAUSED', '已暂停'), ('SKIPPED', '已跳过')], default='RUNNING', max_length=16)),
                ('detail', models.JSONField(default=dict, help_text='步骤详情: 当前处理的文档名、迭代次数等')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='research.researchtask')),
            ],
            options={
                'verbose_name': '任务步骤日志',
                'verbose_name_plural': '任务步骤日志',
                'db_table': 'task_step_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='信息源 URL', max_length=1024)),
                ('source_title', models.CharField(help_text='信息源标题', max_length=512)),
                ('source_type', models.CharField(choices=[('WEB', '网页'), ('PAPER', '学术论文'), ('FINANCIAL', '财务报表'), ('NEWS', '新闻资讯'), ('GOV', '政府公告'), ('OTHER', '其他')], default='WEB', help_text='信息源分类', max_length=16)),
                ('content_text', models.TextField(help_text='抓取到的文本内容')),
                ('relevance_score', models.FloatField(default=0.0, help_text='语义相关度评分 (0.0 ~ 1.0)')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='归属的调研任务', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_contents', to='research.researchtask')),
            ],
            options={
                'verbose_name': '抓取内容',
                'verbose_name_plural': '抓取内容',
                'db_table': 'scraped_content',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('SINGLE', '单模型分析'), ('CROSS', '多模型交叉验证')], default='SINGLE', max_length=16)),
                ('conclusion', models.TextField(help_text='分析结论摘要')),
                ('raw_output', models.JSONField(default=dict, help_text='模型原始输出（完整 JSON）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_config', models.ForeignKey(help_text='使用的模型配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to='llm_manager.llmconfig')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='research.researchtask')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'db_table': 'analysis_result',
            },
        ),
    ]
