# Generated by Codex on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='item_id',
            field=models.CharField(help_text='收藏对象业务 ID (如 report-001/model-001)', max_length=128),
        ),
    ]
