# Generated by Django 6.0.3 on 2026-05-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_favorite_item_id_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'permissions': [('view_audit_log', '查看系统日志'), ('export_audit_log', '导出系统日志')], 'verbose_name': '系统日志', 'verbose_name_plural': '系统日志'},
        ),
    ]
