# Generated by Django 6.0.3 on 2026-05-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_systemlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'permissions': [('create_alert', '创建动态提醒')], 'verbose_name': '推送提醒设置', 'verbose_name_plural': '推送提醒设置'},
        ),
    ]
